server:
  port: 8094

person:
  name: ch
  age: 3
  happy: true
  birth: 2021/12/1
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 3

#springboot的多环境配置：可以选择激活哪一个配置文件
spring:
  profiles:
    active: test
